CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    phone VARCHAR(30),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT chk_users_role
        CHECK (role IN ('OWNER', 'RECEPTIONIST', 'STAFF'))
);

CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_staff_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_staff_tenant_user
        FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CONSTRAINT uq_staff_user UNIQUE (user_id),
    CONSTRAINT uq_staff_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_services_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT uq_services_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT chk_services_price CHECK (price >= 0),
    CONSTRAINT chk_services_duration CHECK (duration_minutes > 0)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(30),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT uq_customers_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_appointments_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_appointments_tenant_customer
        FOREIGN KEY (tenant_id, customer_id)
        REFERENCES customers (tenant_id, id),
    CONSTRAINT fk_appointments_tenant_staff
        FOREIGN KEY (tenant_id, staff_id)
        REFERENCES staff (tenant_id, id),
    CONSTRAINT fk_appointments_tenant_service
        FOREIGN KEY (tenant_id, service_id)
        REFERENCES services (tenant_id, id),
    CONSTRAINT chk_appointments_status
        CHECK (status IN ('CONFIRMED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_appointments_time_range CHECK (end_time > start_time)
);

CREATE INDEX idx_users_tenant ON users (tenant_id);
CREATE INDEX idx_staff_tenant_active ON staff (tenant_id, active);
CREATE INDEX idx_services_tenant_active ON services (tenant_id, active);
CREATE INDEX idx_customers_tenant_name
    ON customers (tenant_id, last_name, first_name);
CREATE INDEX idx_customers_tenant_phone ON customers (tenant_id, phone);
CREATE INDEX idx_customers_tenant_email ON customers (tenant_id, email);
CREATE INDEX idx_appointments_tenant_staff_time
    ON appointments (tenant_id, staff_id, start_time, end_time)
    WHERE status <> 'CANCELLED';
CREATE INDEX idx_appointments_tenant_status_start
    ON appointments (tenant_id, status, start_time);
CREATE INDEX idx_appointments_tenant_customer_start
    ON appointments (tenant_id, customer_id, start_time DESC);
CREATE INDEX idx_appointments_tenant_service
    ON appointments (tenant_id, service_id);
