CREATE TABLE staff_weekly_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    day_of_week VARCHAR(9) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    CONSTRAINT fk_staff_weekly_hours_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_staff_weekly_hours_tenant_staff
        FOREIGN KEY (tenant_id, staff_id) REFERENCES staff (tenant_id, id),
    CONSTRAINT uq_staff_weekly_hours_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT uq_staff_weekly_hours_window
        UNIQUE (staff_id, day_of_week, start_time, end_time),
    CONSTRAINT chk_staff_weekly_hours_day
        CHECK (day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )),
    CONSTRAINT chk_staff_weekly_hours_time_range CHECK (end_time > start_time)
);

CREATE TABLE staff_availability_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    exception_date DATE NOT NULL,
    type VARCHAR(20) NOT NULL,
    start_time TIME,
    end_time TIME,
    note VARCHAR(255),
    CONSTRAINT fk_staff_availability_exceptions_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id),
    CONSTRAINT fk_staff_availability_exceptions_tenant_staff
        FOREIGN KEY (tenant_id, staff_id) REFERENCES staff (tenant_id, id),
    CONSTRAINT uq_staff_availability_exceptions_tenant_id_id UNIQUE (tenant_id, id),
    CONSTRAINT chk_staff_availability_exceptions_type
        CHECK (type IN ('UNAVAILABLE', 'CUSTOM_HOURS')),
    CONSTRAINT chk_staff_availability_exceptions_time_range
        CHECK (
            (start_time IS NULL AND end_time IS NULL)
            OR (
                start_time IS NOT NULL
                AND end_time IS NOT NULL
                AND end_time > start_time
            )
        ),
    CONSTRAINT chk_staff_availability_exceptions_custom_hours
        CHECK (
            type <> 'CUSTOM_HOURS'
            OR (start_time IS NOT NULL AND end_time IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_staff_availability_exceptions_all_day
    ON staff_availability_exceptions (staff_id, exception_date)
    WHERE type = 'UNAVAILABLE' AND start_time IS NULL;

CREATE UNIQUE INDEX uq_staff_availability_exceptions_window
    ON staff_availability_exceptions (
        staff_id,
        exception_date,
        type,
        start_time,
        end_time
    )
    WHERE start_time IS NOT NULL;

CREATE INDEX idx_staff_weekly_hours_tenant_staff_day
    ON staff_weekly_hours (tenant_id, staff_id, day_of_week);

CREATE INDEX idx_staff_availability_exceptions_tenant_staff_date
    ON staff_availability_exceptions (tenant_id, staff_id, exception_date);
