spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bookflow
spring.datasource.username=bookflow
spring.datasource.password=bookflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true